version: "3.1"

services:
  web:
    image: img-qownnotes-api
    build: .
#    container_name: qownnotes-api
    ports:
      - "8080:8080"
    volumes:
      - ./var/app.db:/var/www/var/app.db
    environment:
      - TZ=Europe/Vienna
      - MATOMO_URL=http://p.qownnotes.org
