name: Build Webpage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dev container for testing
      run: cd docker && docker-compose build && docker-compose up
    - name: Run tests
      run: cd docker && ./run-tests
    - run: docker build .
