name: Build Webpage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt -y --no-install-recommends install ca-certificates curl git php7.4-cli php7.4-curl php7.4-json php7.4-mbstring php7.4-xml php7.4-gmp composer
    - name: Composer install
      run: composer install
    - name: Run tests
      run: env SYMFONY_PHPUNIT_VERSION=8 vendor/bin/simple-phpunit
    - name: Try to build docker image
      run: docker build .
