name: Build Webpage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd docker && docker-compose build php-fpm && ./run-tests
    - run: docker build .
